services:

  db-postgres:
    image: postgres:16.1-alpine
    container_name: db_aop
    environment:
      POSTGRES_DB: aop_db
      POSTGRES_USER: aop
      POSTGRES_PASSWORD: aop
    ports:
      - "5433:5432"


