spring:
  application:
    name: Aop

  datasource:
    url: jdbc:postgresql://localhost:5433/aop_db
    username: aop
    password: aop
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.type: true
      hibernate.use_sql_comments: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    user: aop
    password: aop

task:
  limit-downloads: 100

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui